targets:
  $default:
    builders:
      envied:
        enabled: True

builders:
  envied:
    import: "package:envied/src/generator/builder.dart"
    builder_factories: ["enviedBuilder"]
    build_extensions:
      .dart:
        - envied.g.dart
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
